import requests
import json

# Replace with your app name
APP_NAME = "fathi-cv-compiler-f846f2d55ec9"
URL = f"https://{APP_NAME}.herokuapp.com/compile"


# Simple LaTeX to test the photo and the Raleway font
latex_content = r"""
\documentclass[10pt,a4paper]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[default]{raleway}
\usepackage{graphicx}

\begin{document}
\begin{center}
    {\Huge Fathi BELMKADEM} \\
    \vspace{20pt}
    % This tests if your profile.jpg was correctly baked into the image
    \includegraphics[width=4cm]{profile.jpg} \\
    \vspace{20pt}
    \textbf{Heroku Compilation Status: SUCCESS}
\end{center}

\section*{Verification}
This PDF was generated by a Dockerized LaTeX instance on Heroku.
\begin{itemize}
    \item Font: Raleway (FlowCV Style)
    \item Image: Loaded from server-side storage
    \item Engine: PDFLaTeX
\end{itemize}
\end{document}
"""

print(f"Sending request to {URL}...")

try:
    response = requests.post(URL, json={"latex_code": latex_content}, timeout=60)
    
    if response.status_code == 200:
        with open("cv_test_result.pdf", "wb") as f:
            f.write(response.content)
        print("🎉 SUCCESS! Open 'cv_test_result.pdf' to see the result.")
    else:
        print(f"❌ Error {response.status_code}:")
        # Try to print the JSON error details if they exist
        try:
            print(response.json().get("details", "Check heroku logs for info."))
        except:
            print(response.text)

except Exception as e:
    print(f"📡 Connection error: {e}")